### ISSUE TITLE
There doesn't seems to be an DOXYGEN option on the left Application panel

### ISSUE THREAD

**Issue by jimzenn** [TimothyHelton/cpp_project_template#10]
I can create one myself, however, DOXYGEN is not in the target dropdown too.

**Comment by jimzenn** [comment]
<img width="795" alt="screen shot 2018-10-25 at 01 25 21" src="https://user-images.githubusercontent.com/7279131/47486290-df1cd180-d7f4-11e8-94fc-0069068389fb.png">

**Comment by TimothyHelton** [comment]
Hi Jim-Zenn,

I just reran the steps listed in the README.

```bash
curl -O https://raw.githubusercontent.com/TimothyHelton/cpp_project_template/master/new_cpp_project.sh
chmod u+x new_cpp_project.sh
./new_cpp_project.sh NewProjectName
```

Here's how the CLion -> Edit Configurations -> Application Doxygen window looked for me. 

<img width="1068" alt="screen shot 2018-10-26 at 6 15 52 am" src="https://user-images.githubusercontent.com/7132188/47565866-1ec3e600-d8e7-11e8-84fd-724e710a1e1f.png">

Would you please try to copy and paste the commands again and let me know if it works?

Thanks,
Tim
